heat_template_version: 2016-04-08

description: deploys a dedicated system user and mysql as database server

parameters:
  example_net:
    type: string
  security_group:
    type: string
  ssh_keys: 
    type: comma_delimited_list
  name: 
    type: string
  image:
    type: string  
  flavor:
    type: string

resources:

  db_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: example_net}
      security_groups: 
        - default
        - { get_param: security_group }

  db_volume:
   type: OS::Cinder::Volume
   properties:
     description: db volume 
     name: db volume
     size: 50 

  db_server:
    type: OS::Nova::Server
    depends_on: db_port
    properties:
      user_data_format: RAW
      user_data: { get_resource: cloud-init-config }
      image: { get_param: image }
      flavor: { get_param: flavor }
      name: { get_param: name }
      networks:
        - port: { get_resource: db_port }

  db_volume_attach:
    depends_on: [ db_server, db_volume ]
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: db_server }
      volume_id: { get_resource: db_volume }

  cloud-init-config:
   # cloud init demo resource
   type: OS::Heat::CloudConfig
   properties:
     cloud_config:
       runcmd:
         - [ /root/install_db.sh ]
       write_files:
         -  content: { get_file: scripts/install_db.sh }
            permissions: 0700
            path: /root/install_db.sh
       users:
           - name: workshop
             gecos:  Workshop user
             lock-passwd: false
             sudo: ALL=(ALL) NOPASSWD:ALL
             shell: /bin/bash
             ssh-authorized-keys: { get_param: ssh_keys }
       fs_setup:
           - device: /dev/vdb
             partition: none
             label: db_volume
             filesystem: ext4
       mounts:
           - [ "LABEL=db_volume", "/var/lib/mysql" ]
