heat_template_version: 2016-04-08
#
# you can deploy this template using the following command:
# 'openstack stack create -t 02b_routed_network.yaml routed_network_example'
# 

description: deploy a network and a subnet plus a router to connect them both. 

parameters:
 public_network:
  type: string
  default: ext-net
            
resources:
  example_net:
    type: OS::Neutron::Net
    properties: 
      name: example network

  example_subnet:
    type: OS::Neutron::Subnet
    depends_on: example_net
    properties:
      name: example subnet
      dns_nameservers:
        - 8.8.8.8
        - 8.8.4.4
      network: {get_resource: example_net}
      ip_version: 4
      cidr: 10.0.0.0/8
      allocation_pools:
      - {start: 10.0.0.10, end: 10.255.255.250}

  example_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: {"network": { get_param: public_network }}
      name: example network router

  example_subnet_connect:
    type: OS::Neutron::RouterInterface
    depends_on: [ example_router, example_subnet ]
    properties:
      router: { get_resource: example_router }
      subnet: { get_resource: example_subnet }

